lib/index.js
script/extract.js
script/gender.yml
test.js

This adds the code support for https://github.com/get-alex/alex/issues/210

Add optional condition for friendlier messaging

---

rules.md
script/ablist.yml
test.js

- Add more ableist terms (#44)
- Also fixed a typo ("exacly" vs "exactly")

Add more ableist terms

---

rules.md
script/race.yml

Add Native American slur - e.g. Indian giver

Na action slurs

---

rules.md
script/race.yml

Added more synonyms & suggested links for Roma

Roma race synonyms

---

rules.md
script/gender.yml

* Ombudsperson(s)
* Ombudspeople
* Mediator

Add alternatives to ombudsman

---

rules.md
script/ablist.yml
test.js

Add `sensible`, `reasonable` alternatives for `sane`

---

rules.md
script/gender.yml
test.js

See <https://radyananda.wordpress.com/2009/06/06/nonsexist-alternative-language-handbook-for-conscious-writers/>
Closes GH-78.

Add more nonsexist alternatives

---

data/en/ablist.yml
lib/factory.js
rules.md
script/generate.js
test.js

Related-to: GH-31.
Closes GH-32.

Add support for case-sensitive matches

---

data/en/suicide.yml
rules.md
test.js

Add another `hang` alternative

---

data/en/condescending.yml
rules.md

Based on the discussion in https://github.com/get-alex/alex/issues/253 💛 
Did this while listening to a presentation so please let me know if I missed something 😂

Added more variations of condescending terms

---

data/en/suicide.yml

Added note about contagion to suicide.yml.

---

data/en/gender.yml
test.js

Add more gender synonyms and sources

---

data/en/ablist.yml

Add alternative inconsiderate term for people with a cleft lip

---

data/en/ablist.yml

Add checks for muscular dystrophy

---

data/en/race.yml
rules.md

Based on the list at https://twitter.com/chadloder/status/1203483182529560576.

Add alternatives for some stereotypes involving Native Americans and other indigenous peoples

---

package.json

Forgot to add myself as a contributor earlier!

Add contributor

---

data/en/race.yml
rules.md

Add `grandfathered` and related words

---

data/en/gender.yml
rules.md

Add `maiden flight`, suggesting `first flight`

---

data/en/gender.yml

Solves https://github.com/get-alex/alex/issues/317
*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [ ] If applicable, I’ve added docs and tests
Confused about plural words

Fix missing plural

---

lib/factory.js
test.js

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests
This will be rendered by editors.

Add message `url`
